### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jo-mueller** [threedle/iSeg#1]
Dear iSeg authors,

I just stumbled over this repository and it looks like a super-cool tool. I work primarily in a biological-context, for which [napari](https://napari.org/stable/) is the working-horse when it comes to visualization, rendering and interaction (see, for instance, [this repo](https://github.com/haesleinhuepf/napari-process-points-and-surfaces)). I was thinking about turning your tool into an interactive plugin for napari (which is relatively easy, code-wise), but I did not want to start working on anything before ing the authors - you - for your consent, as there is currently no license on this repository. 

If you were to add a permissive license such as BSD-3, I could freely use your code while of course adding a copy of your license to a to-be-created repository.

Let me know what you think :)

**Comment by itailang** [comment]
Dear @jo-mueller,

I appreciate your interest in our project and your kind suggestion! I have added an MIT license to the repo. Feel free to use our code.
