### ISSUE TITLE
Predicted probabilities don't fit size of hammer mesh?

### ISSUE THREAD

**Issue by jo-mueller** [threedle/iSeg#2]
Hi,

I have been working on refactoring the code in this repository a bit for my purposes to run without any visualization built into it. I am able to run the `test_decoder` function without updating the weights with a subsequent click. However, I am running into a minor issue:

The resulting probabilities falling out of the `mlp` application [here](https://github.com/threedle/iSeg/blob/28c5507c39735a80a27279ad1282fd3c073ddc3c/decoder.py#L258):

```Python
prob_tensor = mlp(input_tensor)
```

have the shape `(1, 11595, 2)`, whereas the example hammer mesh has 69384 vertices and 23128 faces. Shouldn't the size of the prediction tensor correspond to the size of the mesh itself (probably the vertices, I suppose)?

For completeness, here's the [link to the refactored files](https://github.com/jo-mueller/iSeg/tree/make-napari-compatible). The relevant par would be [this Jupyter notebook](https://github.com/jo-mueller/iSeg/blob/make-napari-compatible/test_decoder.ipynb).

Thanks in advance!

**Comment by itailang** [comment]
Dear @jo-mueller,

Thank you for your interest in our project!

The example hammer mesh should be downloaded with the scrip [download_demo_data.sh](https://github.com/threedle/iSeg/blob/main/download_demo_data.sh), using the command:
```bash
bash download_demo_data.sh
```

The mesh contains 11,595 vertices and 23,128 faces. The prediction size matches the number of mesh vertices.

Can you please use the script and check if you get these values? Please let me know if you have any issues with that.

Thanks!

**Comment by jo-mueller** [comment]
Hi @itailang ,

Thanks for the quick reply! I am usually working on a windows machine so I am not sure whether bash scripts work there like in the description, so I followed the links to the files from the Google drive. 

I'll try again on a linux machine and then it should work :)

**Comment by itailang** [comment]
Great, thanks!
